version: '3.4'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: safechem_admin
      POSTGRES_PASSWORD: safechem123
      POSTGRES_DB: safechem
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://safechem_admin:safechem123@db:5432/safechem
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:

